FROM php:7.3
RUN apt-get update -y && apt-get install -y --no-install-recommends openssl zip unzip git ffmpeg
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# persistent dependencies
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo

COPY php.ini /usr/local/etc/php/conf.d
COPY php.ini /usr/local/etc/php

WORKDIR /app
COPY . /app
RUN composer install

CMD php artisan migrate
CMD php artisan serve --host=0.0.0.0 --port=8080
EXPOSE 8080