version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rtamediahub/mediahub_rta
    container_name: mediahub_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

#Volumes
volumes:
  dbdata:
