version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rtamediahubacr.azurecr.io/mediahub
    container_name: mediahub_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mediahub

  db:
    image: mysql:5.7
    container_name: mediahub_db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mediahub_db
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mediahub

  nginx:
    image: nginx:1.17-alpine
    container_name: mediahub-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - mediahub

  connector:
    image: abobija/ssh
    container_name: connector
    depends_on:
      - app
    ports:
      - "2222:22"
    restart: unless-stopped
    tty: true
    networks:
      - mediahub

#Docker Networks
networks:
  mediahub:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
