language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/php-coveralls -v
